import { combineReducers } from '@reduxjs/toolkit';

import {
  accounts,
  activePopup,
  addresses,
  allNetworksAccounts,
  assetLogos,
  assets,
  assetTickers,
  balances,
  config,
  currentLocale,
  currentNetwork,
  customCodes,
  customMatcher,
  customNodes,
  idleOptions,
  localState,
  messages,
  nftConfig,
  nfts,
  notifications,
  origins,
  permissionsUiState,
  selectedAccount,
  state,
  swappableAssetIdsByVendor,
  uiState,
  usdPrices,
} from '../../store/reducers/updateState';

export const reducer = combineReducers({
  accounts,
  activePopup,
  addresses,
  allNetworksAccounts,
  assetLogos,
  assets,
  assetTickers,
  balances,
  config,
  currentLocale,
  currentNetwork,
  customCodes,
  customMatcher,
  customNodes,
  idleOptions,
  localState,
  messages,
  nftConfig,
  nfts,
  notifications,
  origins,
  permissionsUiState,
  selectedAccount,
  state,
  swappableAssetIdsByVendor,
  uiState,
  usdPrices,
});
