/**
 * Matcher API Service
 * Handles DEX matcher endpoints for trading operations
 */
import {
  type UseMutationResult,
  type UseQueryResult,
  useMutation,
  useQuery,
} from '@tanstack/react-query';
import * as ds from 'data-service';
import { getExchangeTxList } from '@/lib/data-service/api/transactions/transactions';
import { apiClient, matcherClient } from '../client';

/**
 * Raw exchange transaction shape returned by the data-service exchange tx list endpoint.
 * Declared at module scope so the queryFn can reference it without a local type alias.
 */
interface RawExchangeTx {
  id: string;
  timestamp: number;
  price: number;
  amount: number;
  order1?: { orderType: string };
}

/**
 * Order Side Enum
 */
export type OrderSide = 'buy' | 'sell';

/**
 * Order Status Enum
 */
export type OrderStatus = 'Accepted' | 'PartiallyFilled' | 'Filled' | 'Cancelled';

/**
 * Order Book Entry
 */
export interface OrderBookEntry {
  price: number;
  amount: number;
}

/**
 * Order Book Response
 */
export interface OrderBook {
  timestamp: number;
  pair: {
    amountAsset: string;
    priceAsset: string;
  };
  bids: OrderBookEntry[];
  asks: OrderBookEntry[];
}

/**
 * Order Interface
 * Matches the order shape in both history responses and the place-order response `message` field.
 * `assetPair.amountAsset / priceAsset` are `string | null`: null means native DCC (per Dcc matcher docs
 * "DCC, or null, or omitted field means DCC/DCC").
 */
export interface Order {
  id: string;
  /** Direction: "buy" or "sell" */
  type: OrderSide;
  /** Execution style: "limit" or "market" (returned by history endpoints) */
  orderType: 'limit' | 'market';
  amount: number;
  price: number;
  timestamp: number;
  expiration: number;
  matcherFee: number;
  status: OrderStatus;
  assetPair: {
    amountAsset: string | null;
    priceAsset: string | null;
  };
  filled: number;
  filledFee?: number;
  avgFilledPrice?: number;
}

/**
 * Trade/Match Interface
 */
export interface Trade {
  id: string;
  timestamp: number;
  price: number;
  amount: number;
  type: OrderSide; // buyer or seller perspective
  pair: string;
}

/**
 * Order Creation Data
 * Matches the signed order body accepted by the DCC matcher API.
 * Use `order()` from @decentralchain/transactions to produce a properly signed value.
 */
export interface CreateOrderData {
  /** Computed by the order() builder; included in the signed order body. */
  id?: string;
  /** Order side: 'buy' or 'sell' — NOT the limit/market distinction. */
  orderType: 'buy' | 'sell';
  /** LONG: string for amounts that may exceed Number.MAX_SAFE_INTEGER, number for typical amounts. */
  amount: number | string;
  /** LONG: string for prices that may exceed Number.MAX_SAFE_INTEGER, number for typical prices. */
  price: number | string;
  matcherFee: number;
  matcherFeeAssetId?: string | null;
  matcherPublicKey: string;
  assetPair: {
    amountAsset: string | null;
    priceAsset: string | null;
  };
  timestamp: number;
  expiration: number;
  senderPublicKey: string;
  /** Base58-encoded proofs generated by order() signing. */
  proofs: string[];
  version?: number;
}

/**
 * Matcher Settings
 * `orderFee` supports multiple fee modes depending on the matcher configuration.
 * The DCC and Dcc matchers support: dynamic, percent, fixed, and composite (which
 * nests the above under `composite.default`). Always use `getMatcherBaseFee()` to extract
 * the base fee — never access `orderFee.dynamic` directly.
 */
export interface MatcherSettings {
  matcherPublicKey: string;
  matcherVersion: string;
  priceAssets: string[];
  orderFee: MatcherOrderFee;
}

/**
 * All fee modes supported by the Dcc/DCC matcher.
 * At most one of the top-level keys will be present in a given response.
 */
export interface MatcherOrderFee {
  /** Simple dynamic mode: fee scales with order size. */
  dynamic?: { baseFee: number };
  /** Fixed fee in a specific asset. */
  fixed?: { assetId: string | null; minFee: number };
  /** Percent fee based on order amount. */
  percent?: {
    type: 'amount' | 'price' | 'spending' | 'receiving';
    minFee: number;
    minFeeInDcc: number;
  };
  /**
   * Composite mode (used in production): wraps dynamic/percent/fixed under a `default` key,
   * with optional per-pair overrides in `custom` and a discount asset in `discount`.
   */
  composite?: {
    default: MatcherOrderFee;
    custom?: Record<string, MatcherOrderFee>;
    discount?: { assetId: string; value: number };
  };
}

/**
 * Extract the base fee (in dcclets) from any matcher fee configuration.
 * Walks composite nesting and falls back to 300 000 dcclets (0.003 DCC — the
 * protocol default) when the mode is unrecognised or the field is missing.
 *
 * @param fee - The `orderFee` object from `GET /matcher/settings`.
 */
export function getMatcherBaseFee(fee: MatcherOrderFee): number {
  if (fee.dynamic?.baseFee != null) {
    return fee.dynamic.baseFee;
  }
  if (fee.composite?.default != null) {
    return getMatcherBaseFee(fee.composite.default);
  }
  if (fee.fixed?.minFee != null) {
    return fee.fixed.minFee;
  }
  if (fee.percent?.minFeeInDcc != null) {
    return fee.percent.minFeeInDcc;
  }
  // Default DCC/Dcc matcher fee: 0.003 DCC = 300 000 dcclets.
  return 300_000;
}

/**
 * Trading Pair Info
 */
export interface TradingPairInfo {
  amountAsset: string;
  amountAssetName: string;
  amountAssetInfo?: {
    decimals: number;
  };
  priceAsset: string;
  priceAssetName: string;
  priceAssetInfo?: {
    decimals: number;
  };
  created: number;
}

/**
 * Fetch Order Book
 * Returns current bids and asks for a trading pair
 * Uses data-service for proper Money/BigNumber conversion
 *
 * @param amountAsset - Amount asset ID
 * @param priceAsset - Price asset ID
 * @param depth - Number of price levels to return (default 50)
 * @param options - React Query options
 */
export const useOrderBook = (
  amountAsset: string,
  priceAsset: string,
  depth = 50,
  options?: {
    enabled?: boolean;
    refetchInterval?: number;
  },
): UseQueryResult<OrderBook, Error> => {
  return useQuery({
    enabled: !!amountAsset && !!priceAsset && options?.enabled !== false,
    queryFn: async () => {
      // Use data-service which properly converts Money objects
      interface DsOrderEntry {
        amount: { getTokens(): { toNumber(): number } };
        price: { getTokens(): { toNumber(): number } };
      }
      interface DsOrderBook {
        bids: DsOrderEntry[];
        asks: DsOrderEntry[];
        pair: { amountAsset: { id: string }; priceAsset: { id: string } };
      }
      const orderBookData = (await ds.api.matcher.getOrderBook(
        amountAsset,
        priceAsset,
      )) as DsOrderBook;

      // Convert Money objects to numbers (in token units, not smallest units)
      const bids = orderBookData.bids.slice(0, depth).map((bid) => ({
        amount: bid.amount.getTokens().toNumber(),
        price: bid.price.getTokens().toNumber(),
      }));

      const asks = orderBookData.asks.slice(0, depth).map((ask) => ({
        amount: ask.amount.getTokens().toNumber(),
        price: ask.price.getTokens().toNumber(),
      }));

      return {
        asks,
        bids,
        pair: {
          amountAsset: orderBookData.pair.amountAsset.id,
          priceAsset: orderBookData.pair.priceAsset.id,
        },
        timestamp: Date.now(),
      };
    },
    queryKey: ['orderbook', amountAsset, priceAsset, depth],
    // The matcher exposes no WebSocket feed (/ws/v0 is 404 on 2.3.2.9), so the
    // book is polled. 2s rather than 5s: the Angular app this replaced polled at
    // 1s, and a five-second-old book on a trading screen reads as broken. React
    // Query pauses intervals for hidden tabs, so this costs nothing while the
    // user is on another tab — but it is ~2.5x the matcher request volume of the
    // previous setting for tabs that are open and looking at the DEX.
    refetchInterval: options?.refetchInterval ?? 2000,
    // Refetch when the user returns to the tab. Polling is suspended while
    // hidden, so without this the first thing they see is whatever the book
    // looked like when they left.
    refetchOnWindowFocus: true,
    retry: 2, // Retry failed requests up to 2 times
    retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000), // Exponential backoff
    staleTime: 1000,
  });
};

/**
 * Fetch User Orders
 * Returns order history for a specific asset pair and public key.
 * Requires matcher authentication via Timestamp + Signature headers.
 * The signature is generated at login and stored in user.matcherSign (1-day validity).
 * @see GET /matcher/orderbook/{amountAsset}/{priceAsset}/publicKey/{publicKey}
 *
 * @param publicKey - User's base58-encoded public key
 * @param matcherSign - Pre-generated matcher auth { timestamp (ms, future), signature (base58) }
 * @param amountAsset - Optional: filter by amount asset
 * @param priceAsset - Optional: filter by price asset
 * @param options - React Query options
 */
export const useUserOrders = (
  publicKey: string,
  matcherSign: { timestamp: number; signature: string } | undefined,
  amountAsset?: string,
  priceAsset?: string,
  options?: {
    enabled?: boolean;
    refetchInterval?: number;
  },
): UseQueryResult<Order[], Error> => {
  return useQuery({
    enabled:
      !!publicKey &&
      !!matcherSign?.signature &&
      !!amountAsset &&
      !!priceAsset &&
      options?.enabled !== false,
    queryFn: async () => {
      if (!matcherSign) throw new Error('Matcher sign required');
      const { data } = await matcherClient.get<Order[]>(
        `/orderbook/${amountAsset}/${priceAsset}/publicKey/${publicKey}`,
        {
          headers: {
            Signature: matcherSign.signature,
            Timestamp: String(matcherSign.timestamp),
          },
        },
      );
      return data;
    },
    queryKey: ['orders', publicKey, amountAsset, priceAsset, matcherSign?.timestamp],
    refetchInterval: options?.refetchInterval ?? 10000,
    refetchOnWindowFocus: false,
    retry: 0, // matcher auth fails fast — never retry, prevents 400 loop
    staleTime: 5000,
  });
};

/**
 * Fetch Order History
 * Returns all historical orders for a user address.
 * Requires matcher authentication via Timestamp + Signature headers.
 * The signature is generated at login and stored in user.matcherSign (1-day validity).
 * @see GET /matcher/orderbook/{address} and GET /matcher/orderbook/{address}/activeOnly
 *
 * @param address - User address
 * @param matcherSign - Pre-generated matcher auth { timestamp (ms, future), signature (base58) }
 * @param activeOnly - Filter to active orders only
 * @param options - React Query options
 */
export const useOrderHistory = (
  address: string,
  matcherSign: { timestamp: number; signature: string } | undefined,
  activeOnly = false,
  options?: {
    enabled?: boolean;
    refetchInterval?: number;
  },
): UseQueryResult<Order[], Error> => {
  return useQuery({
    enabled: !!address && !!matcherSign?.signature && options?.enabled !== false,
    queryFn: async () => {
      if (!matcherSign) throw new Error('Matcher sign required');
      const status = activeOnly ? '/activeOnly' : '';
      const { data } = await matcherClient.get<Order[]>(`/orderbook/${address}${status}`, {
        headers: {
          Signature: matcherSign.signature,
          Timestamp: String(matcherSign.timestamp),
        },
      });
      return data;
    },
    queryKey: ['orders', 'history', address, activeOnly, matcherSign?.timestamp],
    refetchInterval: options?.refetchInterval ?? 30_000,
    refetchOnWindowFocus: false,
    retry: 2,
    retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
    staleTime: 30_000,
  });
};

/**
 * Fetch Trade History
 * Returns recent trades for a trading pair
 * Note: Trades come from exchange transactions on the blockchain,
 * not from the matcher API. This requires using the data-service.
 *
 * @param amountAsset - Amount asset ID
 * @param priceAsset - Price asset ID
 * @param limit - Number of trades to return
 * @param options - React Query options
 */
export const useTradeHistory = (
  amountAsset: string,
  priceAsset: string,
  limit = 100,
  options?: {
    enabled?: boolean;
    refetchInterval?: number;
  },
): UseQueryResult<Trade[], Error> => {
  return useQuery({
    enabled: !!amountAsset && !!priceAsset && options?.enabled !== false,
    queryFn: async () => {
      const result = await getExchangeTxList({ amountAsset, limit, priceAsset });
      const txs = (result ?? []) as unknown as RawExchangeTx[];
      return txs.map((tx) => ({
        amount: tx.amount,
        id: tx.id,
        pair: `${amountAsset}/${priceAsset}`,
        price: tx.price,
        timestamp: tx.timestamp,
        type: (tx.order1?.orderType === 'sell' ? 'sell' : 'buy') as OrderSide,
      }));
    },
    queryKey: ['trades', amountAsset, priceAsset, limit],
    refetchInterval: options?.refetchInterval ?? 10000,
    refetchOnWindowFocus: false,
    retry: 2,
    retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
    staleTime: 5000,
  });
};

/**
 * Fetch Matcher Settings
 * Returns matcher configuration and supported assets
 *
 * @param options - React Query options
 */
export const useMatcherSettings = (options?: {
  enabled?: boolean;
}): UseQueryResult<MatcherSettings, Error> => {
  return useQuery({
    enabled: options?.enabled !== false,
    queryFn: async () => {
      // Use empty string because matcherClient base URL is already '/matcher'
      const { data } = await matcherClient.get<MatcherSettings>('/');
      return data;
    },
    queryKey: ['matcher', 'settings'],
    staleTime: 300000, // 5 minutes - settings rarely change
  });
};

/**
 * Fetch Trading Pairs
 * Returns all available trading pairs
 *
 * @param options - React Query options
 */
export const useTradingPairs = (options?: {
  enabled?: boolean;
}): UseQueryResult<TradingPairInfo[], Error> => {
  return useQuery({
    enabled: options?.enabled !== false,
    queryFn: async () => {
      const { data } = await matcherClient.get<TradingPairInfo[]>('/orderbook');
      return data;
    },
    queryKey: ['matcher', 'pairs'],
    staleTime: 60000, // 1 minute
  });
};

/**
 * Response envelope from `POST /matcher/orderbook` (place-limit-order) and
 * `POST /matcher/orderbook/market` (place-market-order).
 *
 * Per the official Dcc Matcher API docs, the response is always wrapped:
 * ```json
 * { "success": true, "message": { ...full signed order... }, "status": "OrderAccepted" }
 * ```
 * The `id` lives inside `message`, not at the top level.
 */
export interface PlaceOrderResponse {
  success: boolean;
  message: Order;
  status: 'OrderAccepted';
}

/**
 * Place Order Mutation
 * Creates a new order on the matcher.
 * Returns `PlaceOrderResponse`; access the order ID via `result.message.id`.
 */
export const usePlaceOrder = (): UseMutationResult<PlaceOrderResponse, Error, CreateOrderData> => {
  return useMutation({
    mutationFn: async (orderData: CreateOrderData) => {
      const { data } = await matcherClient.post<PlaceOrderResponse>('/orderbook', orderData);
      return data;
    },
  });
};

/**
 * Cancel Order Mutation
 * Cancels an existing order
 */
export const useCancelOrder = (): UseMutationResult<
  { status: string; message: string },
  Error,
  { orderId: string; sender: string; signature: string }
> => {
  return useMutation<
    { status: string; message: string },
    Error,
    { orderId: string; sender: string; signature: string }
  >({
    mutationFn: async ({ orderId, sender, signature }) => {
      const { data } = await matcherClient.post<{ status: string; message: string }>(
        `/orderbook/${orderId}/cancel`,
        {
          sender,
          signature,
        },
      );
      return data;
    },
  });
};

/**
 * Cancel All Orders Mutation
 * Cancels all active orders for a user
 */
export const useCancelAllOrders = (): UseMutationResult<
  { status: string; message: string },
  Error,
  { sender: string; timestamp: number; signature: string }
> => {
  return useMutation<
    { status: string; message: string },
    Error,
    { sender: string; timestamp: number; signature: string }
  >({
    mutationFn: async ({ sender, timestamp, signature }) => {
      const { data } = await matcherClient.post<{ status: string; message: string }>(
        '/orderbook/cancel',
        {
          sender,
          signature,
          timestamp,
        },
      );
      return data;
    },
  });
};

/**
 * Utility: Calculate order total (price * amount)
 * @param price - Order price
 * @param amount - Order amount
 */
export const calculateOrderTotal = (price: number, amount: number): number => {
  return price * amount;
};

/**
 * Utility: Calculate fill percentage
 * @param order - Order object
 */
export const getOrderFillPercentage = (order: Order): number => {
  if (order.amount === 0) return 0;
  return (order.filled / order.amount) * 100;
};

/**
 * Utility: Check if order is active
 * @param order - Order object
 */
export const isOrderActive = (order: Order): boolean => {
  return order.status === 'Accepted' || order.status === 'PartiallyFilled';
};

/**
 * Utility: Format trading pair
 * @param amountAsset - Amount asset ID or name
 * @param priceAsset - Price asset ID or name
 */
export const formatTradingPair = (amountAsset: string, priceAsset: string): string => {
  return `${amountAsset}/${priceAsset}`;
};

/**
 * 24h market statistics for a trading pair.
 *
 * `hasTrades` distinguishes "no trading activity" from "all values are zero",
 * which matters here: no market on this chain has traded in the last 24h, so
 * the empty case is the common one and the UI must not render it as real data.
 */
export interface MarketStats24h {
  high24h: number;
  low24h: number;
  volume24h: number;
  lastPrice: number;
  priceChange24h: number;
  priceChangePercent24h: number;
  hasTrades: boolean;
}

/** A single candle as data-service returns it — every value is null when no trades occurred. */
interface DataServiceCandle {
  data: {
    time: string;
    open: string | number | null;
    close: string | number | null;
    high: string | number | null;
    low: string | number | null;
    volume: string | number | null;
    txsCount: number;
  } | null;
}

const EMPTY_STATS: MarketStats24h = {
  hasTrades: false,
  high24h: 0,
  lastPrice: 0,
  low24h: 0,
  priceChange24h: 0,
  priceChangePercent24h: 0,
  volume24h: 0,
};

/**
 * Fetch 24h stats for a pair, derived from hourly candles.
 *
 * The matcher has no ticker endpoint — its swagger exposes 36 paths and none of
 * them carry 24h aggregates — so these are computed from data-service candles,
 * the same source the price chart already uses. data-service rejects any request
 * spanning more than 1440 candles, which 24 hourly candles is comfortably under.
 *
 * Before this existed nothing ever wrote high24h/low24h/volume24h or
 * priceChangePercent24h, so the DEX header rendered a permanent "0.00%" next to
 * a green up-arrow regardless of the market.
 */
export const useMarketStats24h = (
  amountAsset: string,
  priceAsset: string,
  options?: { enabled?: boolean; refetchInterval?: number },
): UseQueryResult<MarketStats24h, Error> => {
  return useQuery({
    enabled: options?.enabled !== false && !!amountAsset && !!priceAsset,
    queryFn: async (): Promise<MarketStats24h> => {
      const now = Date.now();
      const response = await apiClient.get<{ data?: DataServiceCandle[] }>(
        `/v0/candles/${amountAsset}/${priceAsset}`,
        { params: { interval: '1h', timeEnd: String(now), timeStart: String(now - 86_400_000) } },
      );

      const traded = (response.data?.data ?? [])
        .map((entry) => entry.data)
        .filter((candle): candle is NonNullable<DataServiceCandle['data']> => {
          // txsCount is the authoritative "did anything trade in this hour" flag;
          // an untraded hour still returns a candle, with every price field null.
          return !!candle && candle.txsCount > 0 && candle.open !== null && candle.close !== null;
        });

      if (traded.length === 0) return EMPTY_STATS;

      const num = (value: string | number | null): number => Number(value ?? 0);
      const first = traded[0];
      const last = traded[traded.length - 1];
      if (!first || !last) return EMPTY_STATS;

      const open = num(first.open);
      const close = num(last.close);
      const change = close - open;

      return {
        hasTrades: true,
        high24h: Math.max(...traded.map((candle) => num(candle.high))),
        lastPrice: close,
        low24h: Math.min(...traded.map((candle) => num(candle.low))),
        priceChange24h: change,
        // Guard open === 0: a zero-priced opening candle would make this Infinity.
        priceChangePercent24h: open > 0 ? (change / open) * 100 : 0,
        volume24h: traded.reduce((sum, candle) => sum + num(candle.volume), 0),
      };
    },
    queryKey: ['marketStats24h', amountAsset, priceAsset],
    // 24h aggregates move far more slowly than the book; a minute is plenty.
    refetchInterval: options?.refetchInterval ?? 60_000,
    retry: 1,
    staleTime: 30_000,
  });
};
