/**
 * Matcher API Service
 * Handles DEX matcher endpoints for trading operations
 */
import {
  type UseMutationResult,
  type UseQueryResult,
  useMutation,
  useQuery,
} from '@tanstack/react-query';
import * as ds from 'data-service';
import { getExchangeTxList } from '@/lib/data-service/api/transactions/transactions';
import { logger } from '@/lib/logger';
import { matcherClient } from '../client';

/**
 * Order Side Enum
 */
export type OrderSide = 'buy' | 'sell';

/**
 * Order Status Enum
 */
export type OrderStatus = 'Accepted' | 'PartiallyFilled' | 'Filled' | 'Cancelled';

/**
 * Order Book Entry
 */
export interface OrderBookEntry {
  price: number;
  amount: number;
}

/**
 * Order Book Response
 */
export interface OrderBook {
  timestamp: number;
  pair: {
    amountAsset: string;
    priceAsset: string;
  };
  bids: OrderBookEntry[];
  asks: OrderBookEntry[];
}

/**
 * Order Interface
 * Matches the order shape in both history responses and the place-order response `message` field.
 * `assetPair.amountAsset / priceAsset` are `string | null`: null means native DCC (per Waves matcher docs
 * "WAVES, or null, or omitted field means WAVES/DCC").
 */
export interface Order {
  id: string;
  /** Direction: "buy" or "sell" */
  type: OrderSide;
  /** Execution style: "limit" or "market" (returned by history endpoints) */
  orderType: 'limit' | 'market';
  amount: number;
  price: number;
  timestamp: number;
  expiration: number;
  matcherFee: number;
  status: OrderStatus;
  assetPair: {
    amountAsset: string | null;
    priceAsset: string | null;
  };
  filled: number;
  filledFee?: number;
  avgFilledPrice?: number;
}

/**
 * Trade/Match Interface
 */
export interface Trade {
  id: string;
  timestamp: number;
  price: number;
  amount: number;
  type: OrderSide; // buyer or seller perspective
  pair: string;
}

/**
 * Order Creation Data
 * Matches the signed order body accepted by the DCC matcher API.
 * Use `order()` from @decentralchain/transactions to produce a properly signed value.
 */
export interface CreateOrderData {
  /** Computed by the order() builder; included in the signed order body. */
  id?: string;
  /** Order side: 'buy' or 'sell' — NOT the limit/market distinction. */
  orderType: 'buy' | 'sell';
  /** LONG: string for amounts that may exceed Number.MAX_SAFE_INTEGER, number for typical amounts. */
  amount: number | string;
  /** LONG: string for prices that may exceed Number.MAX_SAFE_INTEGER, number for typical prices. */
  price: number | string;
  matcherFee: number;
  matcherFeeAssetId?: string | null;
  matcherPublicKey: string;
  assetPair: {
    amountAsset: string | null;
    priceAsset: string | null;
  };
  timestamp: number;
  expiration: number;
  senderPublicKey: string;
  /** Base58-encoded proofs generated by order() signing. */
  proofs: string[];
  version?: number;
}

/**
 * Matcher Settings
 * `orderFee` supports multiple fee modes depending on the matcher configuration.
 * The DCC and Waves matchers support: dynamic, percent, fixed, and composite (which
 * nests the above under `composite.default`). Always use `getMatcherBaseFee()` to extract
 * the base fee — never access `orderFee.dynamic` directly.
 */
export interface MatcherSettings {
  matcherPublicKey: string;
  matcherVersion: string;
  priceAssets: string[];
  orderFee: MatcherOrderFee;
}

/**
 * All fee modes supported by the Waves/DCC matcher.
 * At most one of the top-level keys will be present in a given response.
 */
export interface MatcherOrderFee {
  /** Simple dynamic mode: fee scales with order size. */
  dynamic?: { baseFee: number };
  /** Fixed fee in a specific asset. */
  fixed?: { assetId: string | null; minFee: number };
  /** Percent fee based on order amount. */
  percent?: {
    type: 'amount' | 'price' | 'spending' | 'receiving';
    minFee: number;
    minFeeInWaves: number;
  };
  /**
   * Composite mode (used in production): wraps dynamic/percent/fixed under a `default` key,
   * with optional per-pair overrides in `custom` and a discount asset in `discount`.
   */
  composite?: {
    default: MatcherOrderFee;
    custom?: Record<string, MatcherOrderFee>;
    discount?: { assetId: string; value: number };
  };
}

/**
 * Extract the base fee (in wavelets) from any matcher fee configuration.
 * Walks composite nesting and falls back to 300 000 wavelets (0.003 DCC — the
 * protocol default) when the mode is unrecognised or the field is missing.
 *
 * @param fee - The `orderFee` object from `GET /matcher/settings`.
 */
export function getMatcherBaseFee(fee: MatcherOrderFee): number {
  if (fee.dynamic?.baseFee != null) {
    return fee.dynamic.baseFee;
  }
  if (fee.composite?.default != null) {
    return getMatcherBaseFee(fee.composite.default);
  }
  if (fee.fixed?.minFee != null) {
    return fee.fixed.minFee;
  }
  if (fee.percent?.minFeeInWaves != null) {
    return fee.percent.minFeeInWaves;
  }
  // Default DCC/Waves matcher fee: 0.003 DCC = 300 000 wavelets.
  return 300_000;
}

/**
 * Trading Pair Info
 */
export interface TradingPairInfo {
  amountAsset: string;
  amountAssetName: string;
  amountAssetInfo?: {
    decimals: number;
  };
  priceAsset: string;
  priceAssetName: string;
  priceAssetInfo?: {
    decimals: number;
  };
  created: number;
}

/**
 * Fetch Order Book
 * Returns current bids and asks for a trading pair
 * Uses data-service for proper Money/BigNumber conversion
 *
 * @param amountAsset - Amount asset ID
 * @param priceAsset - Price asset ID
 * @param depth - Number of price levels to return (default 50)
 * @param options - React Query options
 */
export const useOrderBook = (
  amountAsset: string,
  priceAsset: string,
  depth = 50,
  options?: {
    enabled?: boolean;
    refetchInterval?: number;
  },
): UseQueryResult<OrderBook, Error> => {
  return useQuery({
    enabled: !!amountAsset && !!priceAsset && options?.enabled !== false,
    queryFn: async () => {
      // Use data-service which properly converts Money objects
      interface DsOrderEntry {
        amount: { getTokens(): { toNumber(): number } };
        price: { getTokens(): { toNumber(): number } };
      }
      interface DsOrderBook {
        bids: DsOrderEntry[];
        asks: DsOrderEntry[];
        pair: { amountAsset: { id: string }; priceAsset: { id: string } };
      }
      const orderBookData = (await ds.api.matcher.getOrderBook(
        amountAsset,
        priceAsset,
      )) as DsOrderBook;

      // Convert Money objects to numbers (in token units, not smallest units)
      const bids = orderBookData.bids.slice(0, depth).map((bid) => ({
        amount: bid.amount.getTokens().toNumber(),
        price: bid.price.getTokens().toNumber(),
      }));

      const asks = orderBookData.asks.slice(0, depth).map((ask) => ({
        amount: ask.amount.getTokens().toNumber(),
        price: ask.price.getTokens().toNumber(),
      }));

      return {
        asks,
        bids,
        pair: {
          amountAsset: orderBookData.pair.amountAsset.id,
          priceAsset: orderBookData.pair.priceAsset.id,
        },
        timestamp: Date.now(),
      };
    },
    queryKey: ['orderbook', amountAsset, priceAsset, depth],
    refetchInterval: options?.refetchInterval ?? 5000, // 5 seconds for real-time updates
    refetchOnWindowFocus: false, // Don't refetch on window focus to reduce load
    retry: 2, // Retry failed requests up to 2 times
    retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000), // Exponential backoff
    staleTime: 3000, // 3 seconds
  });
};

/**
 * Fetch User Orders
 * Returns all active orders for a specific address
 * Note: This requires proper authentication with the matcher
 * The endpoint expects public key, not address
 *
 * @param publicKey - User's base58-encoded public key
 * @param amountAsset - Optional: filter by amount asset
 * @param priceAsset - Optional: filter by price asset
 * @param options - React Query options
 */
export const useUserOrders = (
  publicKey: string,
  amountAsset?: string,
  priceAsset?: string,
  options?: {
    enabled?: boolean;
    refetchInterval?: number;
  },
): UseQueryResult<Order[], Error> => {
  return useQuery({
    enabled: !!publicKey && !!amountAsset && !!priceAsset && options?.enabled !== false,
    queryFn: async () => {
      const { data } = await matcherClient.get<Order[]>(
        `/orderbook/${amountAsset}/${priceAsset}/publicKey/${publicKey}`,
      );
      return data;
    },
    queryKey: ['orders', publicKey, amountAsset, priceAsset],
    refetchInterval: options?.refetchInterval ?? 10000,
    refetchOnWindowFocus: false,
    retry: 2,
    retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
    staleTime: 5000,
  });
};

/**
 * Fetch Order History
 * Returns historical orders for a user
 *
 * @param address - User address
 * @param activeOnly - Filter to active orders only
 * @param options - React Query options
 */
export const useOrderHistory = (
  address: string,
  activeOnly = false,
  _options?: {
    enabled?: boolean;
  },
): UseQueryResult<Order[], Error> => {
  return useQuery({
    // Disable until matcher authentication is implemented — same blocker as useUserOrders.
    // /orderbook/:address requires EdDSA/HMAC auth header; returns HTTP 400 without it.
    // When Gate 3 is live: re-enable and add authentication header (DCC-198).
    enabled: false, // was: !!address && options?.enabled !== false,
    queryFn: async () => {
      logger.warn('[useOrderHistory] Skipped: matcher authentication not yet wired (DCC-198)');
      return [];

      // Original implementation (requires authentication):
      // const status = activeOnly ? '/activeOnly' : '';
      // const { data } = await matcherClient.get<Order[]>(`/orderbook/${address}${status}`);
      // return data;
    },
    queryKey: ['orders', 'history', address, activeOnly],
    retry: 0,
    staleTime: 30_000, // 30 seconds
  });
};

/**
 * Fetch Trade History
 * Returns recent trades for a trading pair
 * Note: Trades come from exchange transactions on the blockchain,
 * not from the matcher API. This requires using the data-service.
 *
 * @param amountAsset - Amount asset ID
 * @param priceAsset - Price asset ID
 * @param limit - Number of trades to return
 * @param options - React Query options
 */
export const useTradeHistory = (
  amountAsset: string,
  priceAsset: string,
  limit = 100,
  options?: {
    enabled?: boolean;
    refetchInterval?: number;
  },
): UseQueryResult<Trade[], Error> => {
  return useQuery({
    enabled: !!amountAsset && !!priceAsset && options?.enabled !== false,
    queryFn: async () => {
      type RawExchangeTx = {
        id: string;
        timestamp: number;
        price: number;
        amount: number;
        order1?: { orderType: string };
      };
      const result = await getExchangeTxList({ amountAsset, limit, priceAsset });
      const txs = (result.data ?? []) as unknown as RawExchangeTx[];
      return txs.map((tx) => ({
        amount: tx.amount,
        id: tx.id,
        pair: `${amountAsset}/${priceAsset}`,
        price: tx.price,
        timestamp: tx.timestamp,
        type: (tx.order1?.orderType === 'sell' ? 'sell' : 'buy') as OrderSide,
      }));
    },
    queryKey: ['trades', amountAsset, priceAsset, limit],
    refetchInterval: options?.refetchInterval ?? 10000,
    refetchOnWindowFocus: false,
    retry: 2,
    retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
    staleTime: 5000,
  });
};

/**
 * Fetch Matcher Settings
 * Returns matcher configuration and supported assets
 *
 * @param options - React Query options
 */
export const useMatcherSettings = (options?: {
  enabled?: boolean;
}): UseQueryResult<MatcherSettings, Error> => {
  return useQuery({
    enabled: options?.enabled !== false,
    queryFn: async () => {
      // Use empty string because matcherClient base URL is already '/matcher'
      const { data } = await matcherClient.get<MatcherSettings>('/');
      return data;
    },
    queryKey: ['matcher', 'settings'],
    staleTime: 300000, // 5 minutes - settings rarely change
  });
};

/**
 * Fetch Trading Pairs
 * Returns all available trading pairs
 *
 * @param options - React Query options
 */
export const useTradingPairs = (options?: {
  enabled?: boolean;
}): UseQueryResult<TradingPairInfo[], Error> => {
  return useQuery({
    enabled: options?.enabled !== false,
    queryFn: async () => {
      const { data } = await matcherClient.get<TradingPairInfo[]>('/orderbook');
      return data;
    },
    queryKey: ['matcher', 'pairs'],
    staleTime: 60000, // 1 minute
  });
};

/**
 * Response envelope from `POST /matcher/orderbook` (place-limit-order) and
 * `POST /matcher/orderbook/market` (place-market-order).
 *
 * Per the official Waves Matcher API docs, the response is always wrapped:
 * ```json
 * { "success": true, "message": { ...full signed order... }, "status": "OrderAccepted" }
 * ```
 * The `id` lives inside `message`, not at the top level.
 */
export interface PlaceOrderResponse {
  success: boolean;
  message: Order;
  status: 'OrderAccepted';
}

/**
 * Place Order Mutation
 * Creates a new order on the matcher.
 * Returns `PlaceOrderResponse`; access the order ID via `result.message.id`.
 */
export const usePlaceOrder = (): UseMutationResult<PlaceOrderResponse, Error, CreateOrderData> => {
  return useMutation({
    mutationFn: async (orderData: CreateOrderData) => {
      const { data } = await matcherClient.post<PlaceOrderResponse>('/orderbook', orderData);
      return data;
    },
  });
};

/**
 * Cancel Order Mutation
 * Cancels an existing order
 */
export const useCancelOrder = (): UseMutationResult<
  { status: string; message: string },
  Error,
  { orderId: string; sender: string; signature: string }
> => {
  return useMutation<
    { status: string; message: string },
    Error,
    { orderId: string; sender: string; signature: string }
  >({
    mutationFn: async ({ orderId, sender, signature }) => {
      const { data } = await matcherClient.post<{ status: string; message: string }>(
        `/orderbook/${orderId}/cancel`,
        {
          sender,
          signature,
        },
      );
      return data;
    },
  });
};

/**
 * Cancel All Orders Mutation
 * Cancels all active orders for a user
 */
export const useCancelAllOrders = (): UseMutationResult<
  { status: string; message: string },
  Error,
  { sender: string; timestamp: number; signature: string }
> => {
  return useMutation<
    { status: string; message: string },
    Error,
    { sender: string; timestamp: number; signature: string }
  >({
    mutationFn: async ({ sender, timestamp, signature }) => {
      const { data } = await matcherClient.post<{ status: string; message: string }>(
        '/orderbook/cancel',
        {
          sender,
          signature,
          timestamp,
        },
      );
      return data;
    },
  });
};

/**
 * Utility: Calculate order total (price * amount)
 * @param price - Order price
 * @param amount - Order amount
 */
export const calculateOrderTotal = (price: number, amount: number): number => {
  return price * amount;
};

/**
 * Utility: Calculate fill percentage
 * @param order - Order object
 */
export const getOrderFillPercentage = (order: Order): number => {
  if (order.amount === 0) return 0;
  return (order.filled / order.amount) * 100;
};

/**
 * Utility: Check if order is active
 * @param order - Order object
 */
export const isOrderActive = (order: Order): boolean => {
  return order.status === 'Accepted' || order.status === 'PartiallyFilled';
};

/**
 * Utility: Format trading pair
 * @param amountAsset - Amount asset ID or name
 * @param priceAsset - Price asset ID or name
 */
export const formatTradingPair = (amountAsset: string, priceAsset: string): string => {
  return `${amountAsset}/${priceAsset}`;
};
