import { index, layout, type RouteConfig, route } from '@react-router/dev/routes';

export default [
  route('healthz', 'routes/healthz.ts'),
  route('robots.txt', 'routes/robots.txt.ts'),
  route('login', 'pages/Login.tsx'),
  route('api/auth/github', 'routes/api.auth.github.ts'),
  route('api/auth/github/callback', 'routes/api.auth.github.callback.ts'),
  route('api/auth/logout', 'routes/api.auth.logout.ts'),
  layout('Layout.tsx', [
    index('pages/Nodes.tsx'),
    route('chain-health', 'pages/ChainHealth.tsx'),
    route('generator-performance', 'pages/GeneratorPerformance.tsx'),
    route('service-health', 'pages/ServiceHealth.tsx'),
    route('load-test', 'pages/LoadTest.tsx'),
    route('stress-history', 'pages/StressHistory.tsx'),
    route('e2e', 'pages/E2ERunner.tsx'),
    route('treasury', 'pages/Treasury.tsx'),
    route('ci-cd', 'pages/CiCd.tsx'),
    route('operations', 'pages/Operations.tsx'),
  ]),
  route('api/load-test/stream', 'routes/api.load-test.stream.ts'),
  route('api/load-test/history', 'routes/api.load-test.history.ts'),
  route('api/treasury/fund', 'routes/api.treasury.fund.ts'),
  route('api/treasury/scan', 'routes/api.treasury.scan.ts'),
  route('api/treasury/stream', 'routes/api.treasury.stream.ts'),
  route('api/e2e/stream', 'routes/api.e2e.stream.ts'),
  route('api/ci-cd/status', 'routes/api.cicd.status.ts'),
  route('api/sentry/issues', 'routes/api.sentry.issues.ts'),
  route('api/services/health', 'routes/api.services.health.ts'),
  route('api/maven/artifacts', 'routes/api.maven.artifacts.ts'),
] satisfies RouteConfig;
