// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/healthz": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/api/auth/github": {
    params: {};
  };
  "/api/auth/github/callback": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/load-test": {
    params: {};
  };
  "/treasury": {
    params: {};
  };
  "/api/load-test/stream": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/healthz" | "/robots.txt" | "/login" | "/api/auth/github" | "/api/auth/github/callback" | "/api/auth/logout" | "/load-test" | "/treasury" | "/api/load-test/stream";
  };
  "routes/healthz.ts": {
    id: "routes/healthz";
    page: "/healthz";
  };
  "routes/robots.txt.ts": {
    id: "routes/robots.txt";
    page: "/robots.txt";
  };
  "pages/Login.tsx": {
    id: "pages/Login";
    page: "/login";
  };
  "routes/api.auth.github.ts": {
    id: "routes/api.auth.github";
    page: "/api/auth/github";
  };
  "routes/api.auth.github.callback.ts": {
    id: "routes/api.auth.github.callback";
    page: "/api/auth/github/callback";
  };
  "routes/api.auth.logout.ts": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout";
  };
  "Layout.tsx": {
    id: "Layout";
    page: "/" | "/load-test" | "/treasury";
  };
  "pages/Nodes.tsx": {
    id: "pages/Nodes";
    page: "/";
  };
  "pages/LoadTest.tsx": {
    id: "pages/LoadTest";
    page: "/load-test";
  };
  "pages/Treasury.tsx": {
    id: "pages/Treasury";
    page: "/treasury";
  };
  "routes/api.load-test.stream.ts": {
    id: "routes/api.load-test.stream";
    page: "/api/load-test/stream";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/healthz": typeof import("./src/routes/healthz.ts");
  "routes/robots.txt": typeof import("./src/routes/robots.txt.ts");
  "pages/Login": typeof import("./src/pages/Login.tsx");
  "routes/api.auth.github": typeof import("./src/routes/api.auth.github.ts");
  "routes/api.auth.github.callback": typeof import("./src/routes/api.auth.github.callback.ts");
  "routes/api.auth.logout": typeof import("./src/routes/api.auth.logout.ts");
  "Layout": typeof import("./src/Layout.tsx");
  "pages/Nodes": typeof import("./src/pages/Nodes.tsx");
  "pages/LoadTest": typeof import("./src/pages/LoadTest.tsx");
  "pages/Treasury": typeof import("./src/pages/Treasury.tsx");
  "routes/api.load-test.stream": typeof import("./src/routes/api.load-test.stream.ts");
};