name: Publish BLST

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 0.3.16.0)'
        required: true
        default: '0.3.16.0'

permissions:
  contents: read

concurrency:
  group: publish-blst
  cancel-in-progress: false

jobs:
  publish:
    uses: ./.github/workflows/_publish-maven.yml
    secrets: inherit
    with:
      package-path: packages/jvm/blst
      artifact-name: blst
      version: ${{ inputs.version }}
